"""Report for the spike-origin diagnostics, applying the readings predeclared in MUON_CASE.md.

Run from the project root: .venv/bin/python logs/muon_spectra/spike_diagnostics_20260925/report.py
Reads science/<run>/summary.json and arrays.npz; writes report.md and matrices.csv here.
"""

import csv
import json
import math
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
RUNS = ["muon_d8", "muon_d12", "adamw_d8", "adamw_d12"]
KINDS = ["q", "k", "v", "o", "up", "down"]
NS_HALF = 1.05e-3        # f(sigma) = 0.5 for the paper's five-polynomial map (Frobenius-normalized)


def load(run, source):
    root = HERE / source / run
    return json.loads((root / "summary.json").read_text()), np.load(root / "arrays.npz")


def tracked(names, depth):
    """The paper's four relative depths (1-based N/4, N/2, 3N/4, N)."""
    wanted = [max(1, depth * k // 4) for k in (1, 2, 3, 4)]
    return {b: role for b, role in zip(wanted, ["early", "mid", "late", "final"])}


def reading(m):
    f = m["fresh_mean_gradient"]
    if not f["spike_reproduced"]:
        return "not reproduced"
    mean, sink = m["mean_product"]["of_u1v1"] >= 0.5, m["position0"]["of_u1v1"] >= 0.5
    return "mean+sink" if mean and sink else "mean" if mean else "sink" if sink else "distributed"


def band_reading(row):
    if row["ratio"] is None or row["z"] is None:
        return "n/a"
    if row["ratio"] >= 0.5 and row["z"] >= 3:
        return "signal"
    if row["ratio"] < 0.2 or row["z"] < 2:
        return "noise"
    return "mixed"


def fmt(x, p=2):
    if x is None:
        return "–"
    if isinstance(x, str):
        return x
    return f"{x:.{p}f}" if abs(x) >= 10 ** (-p) or x == 0 else f"{x:.1e}"


def bias_section(data):
    """Post hoc (not predeclared): mean Linear inputs versus the bias vectors that enter them.

    Every token's LayerNorm output contains the LN bias; attention outputs contain the V bias
    (attention weights sum to one). Loads final weights from each run's checkpoint on CPU.
    """
    import torch
    out = ["", "## Post hoc: mean inputs versus architectural bias vectors", "",
           "|cos| and norm ratio ‖bias‖/‖x̄‖: Q input vs ln1.bias, up input vs ln2.bias, O input vs v.bias.", "",
           "| run | block | x̄_q·β1 (ratio) | x̄_up·β2 (ratio) | x̄_o·b_v (ratio) |", "|---|---|---|---|---|"]
    for run, (s, arr) in data.items():
        state = torch.load(Path(s["metadata"]["run"]) / "checkpoint.pt", map_location="cpu",
                           weights_only=False)["model"]
        for b in sorted({int(n[5:7]) for n in s["matrices"]}):
            cells = []
            for kind, key in (("q", f"blocks.{b-1}.ln1.bias"), ("up", f"blocks.{b-1}.ln2.bias"),
                              ("o", f"blocks.{b-1}.attn.v.bias")):
                x = arr[f"block{b:02d}.{kind}/mean_input"]
                beta = state[key].float().numpy()
                cells.append(f"{abs(x @ beta) / (np.linalg.norm(x) * np.linalg.norm(beta)):.2f} "
                             f"({np.linalg.norm(beta) / np.linalg.norm(x):.2f})")
            out.append(f"| {run} | {b} | " + " | ".join(cells) + " |")
    return out


def main(source="science"):
    data = {run: load(run, source) for run in RUNS}
    lines = ["# Spike-origin diagnostics: report", "",
             "Generated by `report.py` from `science/*/summary.json`; readings as predeclared in",
             "`research/adamw_spectra/MUON_CASE.md`. u1, v1 = top singular pair of the saved state",
             "(Muon momentum ×(1−μ), AdamW first moment); Ḡ = mean fresh gradient over 64 × 524,288",
             "never-trained tokens at the final weights.", ""]
    # ---- instrument
    lines += ["## Instrument", "", "| run | val NLL recorded | measured | max recon err | max hook-vs-grad | fresh NLL (mean) |",
              "|---|---|---|---|---|---|"]
    for run, (s, _) in data.items():
        g = s["gates"]
        lines.append(f"| {run} | {g['validation_nll']['recorded']:.5f} | {g['validation_nll']['measured']:.5f} | "
                     f"{g['reconstruction']['max_relative_error']:.1e} | {g['hook_vs_gradient']:.1e} | "
                     f"{np.mean(s['fresh_losses']):.4f} |")
    # ---- per-matrix table (tracked depths) and CSV of all matrices
    rows = []
    for run, (s, arr) in data.items():
        depth = int(run.split("_d")[1])
        roles = tracked(s["matrices"], depth)
        for name, m in s["matrices"].items():
            block, kind = int(name[5:7]), name.split(".")[1]
            f, mp, p0, tk = m["fresh_mean_gradient"], m["mean_product"], m["position0"], m["tokens"]
            bands = {b["band"]: b for b in m["bands"]}
            rows.append({
                "run": run, "block": block, "role": roles.get(block, ""), "kind": kind,
                "rho1_state": m["reference"]["rho1"], "rho1_fresh": f["rho1"],
                "rho1_1M_batch": m["noise"]["pair_mean_rho1"],
                "median_state": m["reference"]["median_normalized"],
                "crossfit_over_sigma1": f["u1v1_over_in_sample_sigma1"], "z1": bands["mode1"]["z"],
                "align_u1": f["u1_alignment"], "align_v1": f["v1_alignment"],
                "reading": reading(m), "mean_share": mp["of_u1v1"], "pos0_share": p0["of_u1v1"],
                "first4_share": p0["first4_of_u1v1"], "sign_consistency": tk["sign_consistency"],
                "top1pct": tk["top1pct_share_of_abs"], "cos_meanx_v1": mp["cos_mean_input_v1"],
                "cos_meangrad_u1": mp["cos_mean_grad_u1"], "cos_pos0x_v1": p0["cos_pos0_input_v1"],
                "v1_participation": m["reference"]["v1"]["participation"],
                "u1_participation": m["reference"]["u1"]["participation"],
                "meanx_participation": mp["mean_input"]["participation"],
                **{f"band_{b}_ratio": bands[b]["ratio"] for b in bands},
                **{f"band_{b}_z": bands[b]["z"] for b in bands},
                **{f"band_{b}_reading": band_reading(bands[b]) for b in bands},
                "ns_in_sample": m["ns_weighted_descent"]["in_sample"],
                "ns_cross_fitted": m["ns_weighted_descent"]["cross_fitted"],
                "edge_over_frob": m["noise"]["edge_state_over_state_frobenius"],
                "edge2_over_frob": m["noise"]["edge2_state_over_state_frobenius"],
                "modes_above_edge2": m["noise"]["modes_above_edge2"]})
    with open(HERE / ("matrices.csv" if source == "science" else f"matrices_{source}.csv"), "w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    lines += ["", "## Spike reproduction and attribution (tracked depths)", "",
              "crossfit/σ1 = u1ᵀḠv1 over the state's σ1 (≈1: the spike is a current population-gradient direction).",
              "Shares are fractions of u1ᵀḠv1. Reading: mean ≥0.5 token-mean product; sink ≥0.5 position-0 tokens.", "",
              "| run | depth | kind | ρ1 state | ρ1 fresh Ḡ | ρ1 1M batch | crossfit/σ1 (z) | align u1/v1 | reading | mean share | pos0 share | sign cons. | top-1% |",
              "|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        if not r["role"]:
            continue
        lines.append(f"| {r['run']} | {r['role']} | {r['kind']} | {fmt(r['rho1_state'])} | {fmt(r['rho1_fresh'])} | "
                     f"{fmt(r['rho1_1M_batch'])} | {fmt(r['crossfit_over_sigma1'])} ({fmt(r['z1'], 0)}) | "
                     f"{fmt(r['align_u1'])}/{fmt(r['align_v1'])} | {r['reading']} | {fmt(r['mean_share'])} | "
                     f"{fmt(r['pos0_share'])} | {fmt(r['sign_consistency'])} | {fmt(r['top1pct'])} |")
    # ---- reading counts
    lines += ["", "Reading counts over all body matrices:", ""]
    for run in RUNS:
        counts = {}
        for r in rows:
            if r["run"] == run:
                counts[r["reading"]] = counts.get(r["reading"], 0) + 1
        by_kind = {k: sorted({r["reading"] for r in rows if r["run"] == run and r["kind"] == k}) for k in KINDS}
        lines.append(f"- {run}: {counts}; by kind {by_kind}")
    # ---- bands
    band_names = ["mode1", "modes2-5", "to_q0.1", "q0.1-q0.5", "q0.5-q0.9", "below_q0.9"]
    lines += ["", "## Cross-fitted descent by band", "",
              "Median over all body matrices of cross-fitted/in-sample; counts of signal/mixed/noise readings",
              "(signal: ratio ≥ 0.5 and z ≥ 3; noise: ratio < 0.2 or z < 2).", "",
              "| run | " + " | ".join(band_names) + " |", "|---|" + "---|" * len(band_names)]
    for run in RUNS:
        cells = []
        for b in band_names:
            vals = [r[f"band_{b}_ratio"] for r in rows if r["run"] == run and r.get(f"band_{b}_ratio") is not None]
            reads = [r[f"band_{b}_reading"] for r in rows if r["run"] == run and f"band_{b}_reading" in r]
            cells.append(f"{np.median(vals):.2f} ({reads.count('signal')}/{reads.count('mixed')}/{reads.count('noise')})")
        lines.append(f"| {run} | " + " | ".join(cells) + " |")
    lines += ["", "Final block, per kind (ratio, z):", "", "| run | kind | " + " | ".join(band_names) + " |",
              "|---|---|" + "---|" * len(band_names)]
    for r in rows:
        if r["role"] == "final":
            lines.append(f"| {r['run']} | {r['kind']} | " + " | ".join(
                f"{fmt(r[f'band_{b}_ratio'])} ({fmt(r[f'band_{b}_z'], 0)})" for b in band_names) + " |")
    # ---- noise and NS
    lines += ["", "## Noise edge and NS weighting", "",
              f"Edges are the state's noise level at its EMA, over the state's Frobenius norm; NS reaches f=0.5 near {NS_HALF:.2e}.",
              "", "| run | kind | median edge/‖R‖ (top) | median edge2/‖R‖ (bulk) | median modes above edge2 | NS in-sample | NS cross-fitted |",
              "|---|---|---|---|---|---|---|"]
    for run in RUNS:
        for kind in KINDS:
            sel = [r for r in rows if r["run"] == run and r["kind"] == kind]
            lines.append(f"| {run} | {kind} | {np.median([r['edge_over_frob'] for r in sel]):.2e} | "
                         f"{np.median([r['edge2_over_frob'] for r in sel]):.2e} | "
                         f"{np.median([r['modes_above_edge2'] for r in sel]):.0f} | "
                         f"{np.median([r['ns_in_sample'] for r in sel]):.3f} | "
                         f"{np.median([r['ns_cross_fitted'] for r in sel]):.3f} |")
    # ---- shared factors
    lines += ["", "## Shared factors (|cos| between state singular vectors; random ≈ 0.044)", "",
              "| run | block | v1 q·k | v1 q·v | v1 k·v | v1 up·q | u1 o·down | u1 o·final o | u1 down·final down | v1(v)·x̄(v) |",
              "|---|---|---|---|---|---|---|---|---|---|"]
    for run, (s, arr) in data.items():
        blocks = sorted({int(n[5:7]) for n in s["matrices"]})
        last = blocks[-1]
        vec = lambda b, k, w: arr[f"block{b:02d}.{k}/state_{w}"]
        c = lambda a, b: abs(float(a @ b) / (np.linalg.norm(a) * np.linalg.norm(b)))
        for b in blocks:
            lines.append(f"| {run} | {b} | {c(vec(b,'q','v1'), vec(b,'k','v1')):.2f} | {c(vec(b,'q','v1'), vec(b,'v','v1')):.2f} | "
                         f"{c(vec(b,'k','v1'), vec(b,'v','v1')):.2f} | {c(vec(b,'up','v1'), vec(b,'q','v1')):.2f} | "
                         f"{c(vec(b,'o','u1'), vec(b,'down','u1')):.2f} | {c(vec(b,'o','u1'), vec(last,'o','u1')):.2f} | "
                         f"{c(vec(b,'down','u1'), vec(last,'down','u1')):.2f} | "
                         f"{c(vec(b,'v','v1'), arr[f'block{b:02d}.v/mean_input']):.2f} |")
    # ---- token-count scaling
    lines += ["", "## Fresh-gradient concentration versus token count (median over matrices of each kind)", ""]
    for run, (s, _) in data.items():
        tokens = [e["tokens"] for e in next(iter(s["matrices"].values()))["scaling"]]
        lines.append(f"{run}: tokens " + ", ".join(f"{t/2**20:.1f}M" for t in tokens))
        for kind in KINDS:
            sel = [m["scaling"] for n, m in s["matrices"].items() if n.endswith("." + kind)]
            rho = np.median([[e["rho1"] for e in sc] for sc in sel], axis=0)
            ratio = np.median([[e["sigma1_over_median"] for e in sc] for sc in sel], axis=0)
            lines.append(f"- {kind}: ρ1 " + " ".join(f"{x:.2f}" for x in rho) +
                         " | σ1/median " + " ".join(f"{x:.0f}" for x in ratio))
    # ---- structure
    lines += ["", "## Forward structure (64 fresh sequences)", "",
              "Attention mass on key 0, mean over queries t ≥ 1 (uniform causal baseline ≈ 0.012) and t ≥ 256 (baseline ≈ 0.003):", ""]
    for run, (s, _) in data.items():
        att = s["structure"]["attention_to_position0"]
        lines.append(f"- {run}: " + "; ".join(
            f"b{i+1} mean {np.mean(a[0]):.3f} max {np.max(a[0]):.2f}/{np.max(a[1]):.2f}" for i, a in enumerate(att)))
        res = s["structure"]["residual_stream"]
        lines.append(f"  residual pos0-norm/rest: " + " ".join(f"{e['pos0_norm_over_rest']:.1f}" for e in res) +
                     " | channel max/mean-abs: " + " ".join(f"{e['channel_max_over_mean_abs']:.0f}" for e in res) +
                     " | top channel per layer: " + " ".join(str(e["top_channels"][0]) for e in res))
    lines += bias_section(data)
    if source == "science":
        (HERE / "report.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    import sys
    main(sys.argv[1] if len(sys.argv) > 1 else "science")
